### PR TITLE
More reliable mobile support for mobile 'interrupt' using touchstart

### PR DESCRIPTION
**Pull request by NateSFiverr**
Love the interrupt feature but was having issues on mobile browsers.  I added a quick check to see if touchstart is enabled (mobile) and, if so, added a one-time listener that used any subsequent touch events to interrupt the scrolling event.  For non-touchstart devices (desktop), continue to use the Tween.prophooks callback since it works great on desktop.

possible resolution to this issue?...
https://github.com/flesler/jquery.scrollTo/issues/131

Thanks! Nate Smith

### CODE REVIEW

**Comment by flesler** [comment]
Hi, I was trying to avoid doing that, because it makes the whole thing messier. If the user doesn't touch, the event remains bound beyond the scrollTo duration, that can cause weird side-effects.

Are you sure there's no way solve this more or less in the same way as Desktop?

About the whitespacing, can you merge the commits? Merging it this way would touch all lines.

You can `git reset --soft HEAD^` until you removed all your commits, then create a commit and `git push -f`. That's what I always do.

**Comment by NateSFiverr** [comment]
I see that. Your demo page works fine on my phone as well (iPhone 6 chrome/safari) but on all pages I test within my application--where I'm scrolling on the window (e.g. "$.scrollTo")--the result is that the page scrolls for about 10-20 px, then stops automatically.  

I believe the issue is that mobile browsers can't distinguish between a window scroll via scrollTo and a user physically scrolling.  As a result, the scroll starts then stops almost immediately, since it detects a window scroll (its own in this case).

Hopefully that makes some sense.  I redid my pull request to add a simple one-time listener on the document (targetting "html" and listening for "scroll DOMMouseScroll mousedown mousewheel touchstart" events) that is removed either by executing an interrupt action listed or when the scroll is completed.  If you want to get rid of the "mousedown" listener, no problem. I went back and forth about whether a user clicking should trigger the interrupt.

This approach works in all cases (no need to identify device type) and does not introduce any lag per my testing.

If you already have a full-document selector (like body/html) that I may have missed, then you could even remove the "var $html = $('html');"  part and replace use that existing one to add/remove the interrupt listener.

Would love to know your thoughts. We're using this plugin within our org and would love to integrate these changes directly instead monkey-patching. Great work. Thanks! Nate

**Comment by flesler** [comment]
Hi, to be honest I'll need to test it in detail before proceeding. I'll try to reproduce the problem with my phone asap.
Cannot assume there is a problem without seeing it.

Note that $('html').off() will unbind all handlers from all events from that element.

The unbinding can be done in the `complete()` callback of `animate()`. It's currently only used if user included an `onAfter()` but that can be easily changed.

I'd advise you to monkey-patch for now and upgrade if the change is indeed deployed.
You should be able to do so without changing the plugin's code, you bind your handler when you call the plugin and unbind on `onAfter()`.

**Comment by NateSFiverr** [comment]
Sounds good man and great catch on the risky .off() call / tip on the complete() callback. I'm going to make those changes in my patch.  Take care!

**Comment by NateSFiverr** [comment]
Just wanted to follow up with the change I'm implementing in my environment (incorporating your tips!)  Still can't figure out why the spacing is always f'd up when I push to your branch but take a look if you get the chance! Peace.

**Pull request closed without merging**
