### PR TITLE
require jQuery as a peerDependency

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@flesler bump

**Comment by flesler** [comment]
Hi @graingert, sorry for the delay.
I'm a little afraid of these kind of changes due to the unexpected consequences for those already using the current version after they upgrade.

If I'm not mistaken, they should suddenly see a warning telling them the peerDependency was not loaded right? It might even not fail for that that already have jquery in their local node_modules but do fail on a clean install in production, am I wrong?

This seems like the right step but might require a major release bump, a notice and several complaints.
What do you think?

**Comment by graingert** [comment]
I'm fine with a major release bump

**Comment by flesler** [comment]
Since there no more requests or complaints for this for almost 5 years. I decided to close it :)

**Pull request closed without merging**
