### PR TITLE
Adding a check for Tween to prevent undefined errors in Firefox

### PR DESCRIPTION
**Pull request by crmpicco**

### CODE REVIEW

**Comment by flesler** [comment]
It has nothing to do with Firefox, that is defined by jQuery on all browsers. Isn't this the same as #115?

**Comment by crmpicco** [comment]
Yes it does appear to be the same as #115 . That is the same issue I am experiencing. I am using jQuery 1.7.2 and jQuery Mobile 1.3.1. Maybe this is a useful workaround for those on slightly older versions of jQuery.

**Comment by flesler** [comment]
Not really, you will avoid the exception but then the plugin won't work. That code is not optional.

If you really can't update jQuery and you want to use scrollTo, you can use a version prior to 2.0.
[Version 1.4.14](https://github.com/flesler/jquery.scrollTo/releases/tag/1.4.14) should work with jQuery >= 1.4

**Comment by flesler** [comment]
In any case, I'll close this issue as dup of #115. jQuery.scrollTo 2.0 requires jQuery 1.8 and above, I recently added a mention of that on the docs

**Pull request closed without merging**
