### PR TITLE
Fix bower warning; name should be lowercase.

### PR DESCRIPTION
**Pull request by jdufresne**
The warning:

bower jquery.scrollTo#2.1.2

invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes

### CODE REVIEW

**Comment by flesler** [comment]
Wouldn't this register the package with a new "id"? Or does bower always lower case names?

**Comment by jdufresne** [comment]
> Wouldn't this register the package with a new "id"? Or does bower always lower case names?

Doesn't appear that way. See the output below. Hmm, not sure the best way to remove that warning then.

```
$ ./node_modules/.bin/bower install jquery.scrollto
bower                        ENOTFOUND Package jquery.scrollto not found

$ ./node_modules/.bin/bower install jquery.scrollTo
bower jquery.scrollTo#*         cached https://github.com/flesler/jquery.scrollTo.git#2.1.2
bower jquery.scrollTo#*       validate 2.1.2 against https://github.com/flesler/jquery.scrollTo.git#*
bower jquery#>=1.8              cached https://github.com/jquery/jquery-dist.git#2.2.3
bower jquery#>=1.8            validate 2.2.3 against https://github.com/jquery/jquery-dist.git#>=1.8
bower jquery.scrollTo#^2.1.2   install jquery.scrollTo#2.1.2
bower jquery#>=1.8             install jquery#2.2.3

jquery.scrollTo#2.1.2 bower_components/jquery.scrollTo
└── jquery#2.2.3

jquery#2.2.3 bower_components/jquery
```

**Comment by flesler** [comment]
Seems to me it IS that way. You tried installing the lower case name and it wasn't found, rather than pointing to the same place as jquery.scrollTo.

I'll try to read a bit about this later, but honestly my priority is not breaking stuff for those using it right now.

**Comment by jdufresne** [comment]
Sorry for the confusion. I was answering "Doesn't appear that way" to the 2nd question of "Or does bower always lower case names?".

**Comment by flesler** [comment]
Duplicate #165, leaving that one open because it has fresh info

**Pull request closed without merging**
